name: CI/CD Pipeline - runs tests and deploys Nithub Server

on:
    # push:
    #     branches: ['main']

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm install

    # this job depends on the successful completion of the build job above
    deploy:
        permissions:
            contents: none
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: login to VM and update the app
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  command_timeout: 200m
                  script: |
                      if [ -d "nithub-management-system" ]; then
                        echo "Directory exists. Pulling latest changes."
                        cd nithub-management-system
                        git pull origin main
                        docker compose restart
                      else
                        echo "Directory does not exist. Cloning repository."
                        git clone https://github.com/nithubunilag/user-management-system-backend.git nithub-management-system
                        cd nithub-management-system
                        docker-compose up -d
                      fi
